version: '3'

services:
  db:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdemo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  php:
    build: ./.docker/php
    working_dir: /var/www/dockerdemo
    volumes:
      - ./:/var/www/dockerdemo
    depends_on:
      - db

  web:
    image: nginx
    volumes:
      - ./:/var/www/dockerdemo
      - ./.docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
